// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto
package Status;

/**
 * Protobuf type {@code SmartCar.FilterStatusResponse}
 */
public class FilterStatusResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        FilterStatusResponseOrBuilder{

    private static final long serialVersionUID = 0L;

    // Use FilterStatusResponse.newBuilder() to construct.
    private FilterStatusResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }
    private FilterStatusResponse() {
        filterStatusCurr_ = 0D;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }
    private FilterStatusResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    case 9: {
                        filterStatusCurr_  = input.readDouble();
                        break;
                    }
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }
    public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
        return StatusImpl.internal_static_SmartCar_FilterStatusRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable internalGetFieldAccessorTable() {
        return StatusImpl.internal_static_SmartCar_FilterStatusResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        Status.FilterStatusResponse.class, Status.FilterStatusResponse.Builder.class);
    }

    public static final int STATUS_CURR_FIELD_NUMBER = 1;
    private double filterStatusCurr_;

    /**
     * <code> double filterStatusCurr = 1; </code>
     */
    public double getFilterStatusCurr() {
        return filterStatusCurr_ ;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;
        memoizedIsInitialized = 1;
        return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (filterStatusCurr_ != 0D) {
            output.writeDouble(1, filterStatusCurr_ );
        }
        unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;
        size = 0;
        if (filterStatusCurr_ != 0D) {
            size += com.google.protobuf.CodedOutputStream
                    .computeDoubleSize(1, filterStatusCurr_ );
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof Status.FilterStatusResponse)) {
            return super.equals(obj);
        }
        Status.FilterStatusResponse other = (Status.FilterStatusResponse) obj;
        boolean result = true;
        result = result && (
                java.lang.Double.doubleToLongBits(getFilterStatusCurr())
                        == java.lang.Double.doubleToLongBits(
                        other.getFilterStatusCurr()));
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STATUS_CURR_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                java.lang.Double.doubleToLongBits(getFilterStatusCurr()));
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static Status.FilterStatusResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static Status.FilterStatusResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Status.FilterStatusResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static Status.FilterStatusResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Status.FilterStatusResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }
    public static Status.FilterStatusResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Status.FilterStatusResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static Status.FilterStatusResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Status.FilterStatusResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }
    public static Status.FilterStatusResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Status.FilterStatusResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }
    public static Status.FilterStatusResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() {
        return newBuilder();
    }
    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Status.FilterStatusResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    @Override
    public double filterStatusCurr() {
        return 0;
    }

    /**
     * Protobuf type {@code SmartCar.FilterStatusResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:SmartCar.FilterStatusResponse)
            FilterStatusResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return StatusImpl.internal_static_SmartCar_FilterStatusResponse_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return StatusImpl.internal_static_SmartCar_FilterStatusResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(Status.FilterStatusResponse.class, Status.FilterStatusResponse.Builder.class);
        }

        // Construct using Status.FilterStatusResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }
        @java.lang.Override
        public Builder clear() {
            super.clear();
            filterStatusCurr_  = 0D;
            return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return Status.StatusImpl.internal_static_SmartCar_FilterStatusResponse_descriptor;
        }

        @java.lang.Override
        public Status.FilterStatusResponse getDefaultInstanceForType() {
            return Status.FilterStatusResponse.getDefaultInstance();
        }

        @java.lang.Override
        public Status.FilterStatusResponse build() {
            Status.FilterStatusResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        @java.lang.Override
        public Status.FilterStatusResponse buildPartial() {
            Status.FilterStatusResponse result = new Status.FilterStatusResponse(this);
            result. filterStatusCurr_=  filterStatusCurr_;
            onBuilt();
            return result;
        }

        @java.lang.Override
        public Builder clone() {
            return (Builder) super.clone();
        }
        @java.lang.Override
        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return (Builder) super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return (Builder) super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return (Builder) super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return (Builder) super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof Status.FilterStatusResponse) {
                return mergeFrom((Status.FilterStatusResponse)other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(Status.FilterStatusResponse other) {
            if (other == Status.FilterStatusResponse.getDefaultInstance()) return this;
            if (other.getFilterStatusCurr() != 0D) {
                setFilterStatusCurr(other.getFilterStatusCurr());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
            return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            Status.FilterStatusResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (Status.FilterStatusResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private double filterStatusCurr_ ;

        /**
         * <code> double filterStatusCurr = 1; </code>
         */
        public double getTempCurr() {
            return filterStatusCurr_ ;
        }
        /**
         * <code> double filterStatusCurr = 1; </code>
         */
        public Builder setFilterStatusCurr(double value) {
            filterStatusCurr_ = value;
            onChanged();
            return this;
        }

        /**
         * <code> double filterStatusCurr = 1; </code>
         */
        public Builder clearFilterStatusCurr() {
            filterStatusCurr_  = 0D;
            onChanged();
            return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }

        @Override
        public double filterStatusCurr() {
            return 0;
        }
        // @@protoc_insertion_point(builder_scope:SmartCar.FilterStatusResponse)
    }

    // @@protoc_insertion_point(class_scope:SmartCar.FilterStatusResponse)
    private static final Status.FilterStatusResponse DEFAULT_INSTANCE;
    static {
        DEFAULT_INSTANCE = new Status.FilterStatusResponse();
    }

    public static Status.FilterStatusResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<FilterStatusResponse>
            PARSER = new com.google.protobuf.AbstractParser<FilterStatusResponse>() {
        @java.lang.Override
        public FilterStatusResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new FilterStatusResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<FilterStatusResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<FilterStatusResponse> getParserForType() {
        return PARSER;
    }

    @java.lang.Override
    public Status.FilterStatusResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}
