// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto

package Status;

public interface FilterStatusRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartCar.FilterStatusRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 filterStatus = 1;</code>
     */
    int getFilterStatus();
}
