// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto

package Status;

public interface FilterStatusResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartCar.FilterStatusResponse)
        com.google.protobuf.MessageOrBuilder{

    /**
     * <code>double filterStatusCurr = 1;</code>
     */
    double filterStatusCurr();
}
