// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: status.proto

package Status;

public class StatusImpl {

    private StatusImpl() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartCar_FilterStatusRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartCar_FilterStatusRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartCar_FilterStatusResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartCar_FilterStatusResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016status.proto\022\010SmartCar\">\n\030FilterSta" +
                        "tusRequest\022\017\n\007filterStatus\030\001 \001(\005\022\021\n\t" +
                        "\030\002 \001(\005\"\036\n\rFilterStatusResponse\022\r\n\005filterStatusCurr\030\001 \001" +
                        "(\0012_\n\rStatus\022N\n\rStatus\022\".w" +
                        "earGRPC.FilterStatusRequest\032\027.wearG" +
                        "RPC.FilterStatusResponse0\001B\037\n\rStatusB\014St" +
                        "atusImplP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_SmartCar_FilterStatusRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SmartCar_FilterStatusRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartCar_FilterStatusRequest_descriptor,
                new java.lang.String[] { "FilterStatus"});
        internal_static_SmartCar_FilterStatusResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_SmartCar_FilterStatusResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartCar_FilterStatusResponse_descriptor,
                new java.lang.String[] { "FilterStatusCurr", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
