// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

package Index;

public interface AnalysisResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartCar.AnalysisResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string total = 1;</code>
     */
    java.lang.String getTotal();
    /**
     * <code>string Total = 1;</code>
     */
    com.google.protobuf.ByteString
    getTotalBytes();
}
