// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

package Index;

public class IndexImpl {

    private IndexImpl() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartCar_NumberKmRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartCar_NumberKmRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartCar_AnalysisResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartCar_AnalysisResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016index.proto\022\010SmartCar\"\036\n\rNumberKmRequ" +
                        "est\022\r\n\005Km\030\001 \001(\001\"!\n\016AnalysisResponse\022\017\n\007" +
                        "total\030\001 \001(\t2S\n\013Index\022D\n\013Index" +
                        "\022\027.SmartCar.NumberKmRequest\032\030.SmartCar." +
                        "AnalysisResponse(\0010\001B\035\n\013IndexB\014Index" +
                        "ImplP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_SmartCar_NumberKmRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SmartCar_NumberKmRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartCar_NumberKmRequest_descriptor,
                new java.lang.String[] { "Km", });
        internal_static_SmartCar_AnalysisResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_SmartCar_AnalysisResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartCar_AnalysisResponse_descriptor,
                new java.lang.String[] { "Total", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
