// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: index.proto

package Index;

public interface NumberKmRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartCar.NumberKmRequest)
        com.google.protobuf.MessageOrBuilder {


    /**
     * <code>double Km = 1;</code>
     */
    double getKm();
}
