// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: track.proto

package Track;

public class TrackImpl {

    private TrackImpl() {}
    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartCar_TrackRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartCar_TrackRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_SmartCar_TrackResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_SmartCar_TrackResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }
    private static  com.google.protobuf.Descriptors.FileDescriptor
            descriptor;
    static {
        java.lang.String[] descriptorData = {
                "\n\016activate.proto\022\010SmartCar\"\021\n\017TrackRe" +
                        "quest\"*\n\017TrackResponse\022\027\n\017trackingSta" +
                        "tus\030\001 \001(\t2W\n\010Activate\022K\n\021track" +
                        "\022\031.SmartCar.TrackRequest\032\031.SmartCar" +
                        ".TrackResponse\"\000B\035\n\013ActivateB\014Tra" +
                        "ckImplP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[] {
                        }, assigner);
        internal_static_SmartCar_TrackRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_SmartCar_TrackRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartCar_TrackRequest_descriptor,
                new java.lang.String[] { });
        internal_static_SmartCar_TrackResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_SmartCar_TrackResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_SmartCar_TrackResponse_descriptor,
                new java.lang.String[] { "TrackingStatus", });
    }

    // @@protoc_insertion_point(outer_class_scope)
}
