// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: track.proto

package Track;

public interface TrackRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartCar.TrackRequest)
        com.google.protobuf.MessageOrBuilder{
}
