// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: activate.proto

package Track;

public interface TrackResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:SmartCar.TrackResponse)
        com.google.protobuf.MessageOrBuilder{

    /**
     * <code>string trackingStatus = 1;</code>
     */
    java.lang.String getTrackingStatus();
    /**
     * <code>string trackingStatus = 1;</code>
     */
    com.google.protobuf.ByteString
    getTrackingStatusBytes();
}
